### PR TITLE
Modify @hdgarrood's PR to use Data.Op.

### PR DESCRIPTION
**Pull request by paf31**
This a slightly different take on @hdgarrood's branch, using `Data.Op` for `Option` and dropping `key`. As we add combinators to `Data.Functor.Contravariant.Divisible`, this approach will become more useful, I think.

### CODE REVIEW

**Comment by ethul** [comment]
Thanks! Looks good. I will dig more into this on the weekend.

**Comment by ethul** [comment]
Sorry for the delay, but I think the PR looks great. Before merging, is this intended only for purescript 0.8? I am wondering if we should update the [exports](https://github.com/ethul/purescript-options/pull/13/files#diff-7d27ce0952096d6a0b842daaa76de143R5) and corresponding [imports](https://github.com/ethul/purescript-options/pull/13/files#diff-ad021123e94c96ad962935670f6a8177R9) for 0.7 compatibility? Or we could release this along with 0.8. That works for me too.

Also, do you think this module should be moved to core or contrib once this PR is merged? I am open to either.

**Comment by garyb** [comment]
Probably stick to 0.7 for now, all the core libraries are going to be updated and bumped after 0.8 is released, so it will need updating again anyway.

**Comment by ethul** [comment]
Before publishing to pursuit is this good to move into core?

**Comment by hdgarrood** [comment]
:tada:

**Comment by paf31** [comment]
@ethul If you're okay with it, I think it would be a good addition. @garyb Anything else we need?

**Comment by garyb** [comment]
Nope, :+1: for moving over. Core or contrib?

**Comment by paf31** [comment]
Perhaps `contrib` for now, until we're confident the new API is the right one?

**Comment by garyb** [comment]
Sounds sensible to me.

**Comment by paf31** [comment]
@ethul You should be able to move the repo to `contrib` now, if you like.

**Comment by ethul** [comment]
Thanks! The repo has been moved over

**Comment by paf31** [comment]
Thanks! I've set up a new team.

**Comment by ethul** [comment]
Great, thank you!

**Pull request merged**
